version: '3.3'

networks:
  webapp:
    driver: bridge
  database:
    driver: bridge

services:
  db:
    image: postgres:10.4
    networks:
      - database
    ports:
      - 5432:5432
    env_file:
      - ./db/.env
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: db
    hostname: db
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - back
    networks:
      - webapp
    ports:
      - 3000:3000
    restart: unless-stopped
    command: 
    
